### ISSUE TITLE
Many verses contain strange characters

### ISSUE THREAD

**Issue by Alternate-Existance** [The-Best-Codes/best-bible#32]
**Describe the bug**
Many Bible verse contain strange characters like `[]` or `#`. 

**To Reproduce**
1. Call the `getVerse` function for Genesis 1:2, and see the words in brackets. 
2. Call the `getVerse` function for Genesis 1:6, and see the hashtag at the beginning.

**Expected behavior**
I want the plain-text verse with not strange characters.

**Screenshots**
![Screenshot from 2024-09-09 11-08-43](https://github.com/user-attachments/assets/f6465553-bbb8-49e9-8797-07ea9132b58a)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version 120

**Smartphone:**
 - N/A

**Additional context**
This occurs for any function that returns a verse.

**Comment by The-Best-Codes** [comment]
Hi @Alternate-Existance, release v1.5.8 addresses this issue. Thanks for bringing this to my attention!

https://github.com/The-Best-Codes/best-bible/releases/tag/v1.5.8

**Comment by Alternate-Existance** [comment]
Awesome, thank you! I will update right away! :grinning:
